platform :ios, '8.0'

target 'TWCommonMoudleDemo' do
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'Qiniu'
    
    # ShareSDK
    # 主模块(必须)
    pod 'mob_sharesdk'
    pod 'MOBFoundation'
    
    pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
    pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
    pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
    pod 'mob_sharesdk/ShareSDKPlatforms/Facebook'
    pod 'mob_sharesdk/ShareSDKPlatforms/Line'
    
    pod 'SDWebImage'
    
    pod 'TWFreshLoadingView'
    pod 'TWAlertMessage'


end
